### ISSUE TITLE
SIM-BE-Cannot access local functions on init

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#401]
# Issue

There are some local functions that I cannot access in the simulator's init

```
jsonrpc-1             | Updating transaction status 138 PROPOSING
jsonrpc-1             | Error running consensus Can't get local object 'TowelTechies.__init__.<locals>.default_int_dict'
jsonrpc-1             | Traceback (most recent call last):
jsonrpc-1             |   File "/app/backend/consensus/base.py", line 75, in _run_consensus
jsonrpc-1             |     await asyncio.gather(*tasks)
jsonrpc-1             |   File "/app/backend/consensus/base.py", line 126, in exec_transaction
jsonrpc-1             |     leader_receipt = await leader_node.exec_transaction(transaction)
jsonrpc-1             |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jsonrpc-1             |   File "/app/backend/node/base.py", line 40, in exec_transaction
jsonrpc-1             |     receipt = self.deploy_contract(
jsonrpc-1             |               ^^^^^^^^^^^^^^^^^^^^^
jsonrpc-1             |   File "/app/backend/node/base.py", line 74, in deploy_contract
jsonrpc-1             |     receipt = self.genvm.deploy_contract(
jsonrpc-1             |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
jsonrpc-1             |   File "/app/backend/node/genvm/base.py", line 127, in deploy_contract
jsonrpc-1             |     pickled_object = pickle.dumps(current_contract)
jsonrpc-1             |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jsonrpc-1             | AttributeError: Can't get local object 'TowelTechies.__init__.<locals>.default_int_dict'
jsonrpc-1             | 
jsonrpc-1             | INFO | get_transaction_by_id: EndpointResult(status=<EndpointResultStatus.INFO: 'info'>, message='Starting...', data={}, exception=None)
```

# Context

I've found it while working on https://github.com/yeagerai/hackathon-2024-08-16/pull/1

# Steps to reproduce

Create a contract like:
```py
def MyContract(IContract):
  def __init__(self):
    def local_func():
      pass
    x = local_func
```

**Comment by cristiam86** [comment]
Closed due to the integration with the real GenVM
