### ISSUE TITLE
SIM-BE-Contract deployment sometimes fails with auxiliary classes

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#403]
# Issue
With 2 auxiliary classes, the contract parsing fails

```py
@dataclass
class Sentiment:
    cryptocurrency: str
    positive_sentiment: float


@dataclass
class AnalyzedTweet:
    influencer: str
    tweet: str
    date: str
    cryptocurrency: str
    positive_sentiment: float
    sentiment: Sentiment

class MyContract(IContract):
...
```

The error:
```
traceback:"Traceback (most recent call last):
File "/app/backend/protocol_rpc/endpoint_generator.py", line 29, in endpoint
function_result = function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/backend/protocol_rpc/endpoints.py", line 123, in get_contract_schema_for_code
return node.get_contract_schema(contract_code)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/backend/node/base.py", line 95, in get_contract_schema
return GenVM.get_contract_schema(code)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/backend/node/genvm/base.py", line 225, in get_contract_schema
exec(contract_code, globals(), namespace)
File "<string>", line 15, in <module>
File "<string>", line 21, in AnalyzedTweet
NameError: name 'Sentiment' is not defined
```

**Comment by cristiam86** [comment]
Closed due to the integration with the real GenVM
